name: video_recorder_app
description: "A new and fun Video recording project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  http: ^1.2.1
  intl: ^0.19.0
  file_picker: ^8.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
